service:
  name: prostaid-pdf-generator-lambda

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: prostaid-prod
  region: ${opt:region, 'us-west-2'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  generate-pdfv3:
    handler: handler.generatePDFWeb
    memorySize: 1024 # Setting a higher RAM size to facilitate PDF generation
    events:
      - httpApi: 'POST /generate-pdfv3'
